travis:
  secure:
    BINSTAR_TOKEN: cJDS6KF/qSpG+duhJbLMxHgjga4fGXCoJ3shZ4QGckCE3Cy5ScNuXTgrFmH1G6xd9+VrBZxYzdbbWxtIVS0lyKZQf4yRHDOjg/YWVKjbOUmenFXdFnGjnQ3kj6kWz3h9m+zT0/qQMyj9NMxb43+qsHTHlX96d8P+e3oMLdF4vVALOFp6DNpA0o8E83CawagUinVDnMKNa4IwllU7UHG98G5IdaHXWyNQvW4Q8GYJJtW3ED30eqPehYSzZk3F6hwHNjSu6Y7xZGRgMcib/ugYS54kAlXQS+82NN1j0+QuVmThjWMG986wWov4VMNTs8ZMOUe9f6wMTVFWgOGcqU01wfodaqhPTdW5o+cVRCq2jecRQVeAvK2ECC3qnF94acNvST3XDx59LgX1DgxUuLg0K+zy0h4ebwG9QFnu/koiG+yQdvcU1hErsb1T0ngmjyQogrEdz5RDqZBz9FxdJ5F6c9H/cG0OzYjbaE+OS4Wm+WRl+lMrU8C93qidJwyDpiXTv8iAohxFnDTLTM4Qcu9P6fLsQpnVY68X60M1/D3nZ88LEdZTG6e71NwmAkI7Axt+yZeM218ZCBGB949l5SLfe9CqqIrs8QP+uMl3gjWel8H9VJU2S2T7CFR7GgvAtxy0yiGIrkGOq0vA3FkhTJKPBZBmyb7ZJVtFpeSQnYXz+zA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
